table sales_fact
	lineageTag: 0389bbd2-9a41-4391-af54-d416862af143

	measure 'Total Sales' = SUM(sales_fact[Sales])
		formatString: MXN #,##0
		lineageTag: 6900c6e0-cf1a-40a4-8fdc-d08f487290eb

	measure 'Gross Profit' = SUM(sales_fact[Profit])
		formatString: MXN #,##0
		lineageTag: b36dd91c-737f-49be-9934-f8f3f00ade26

	measure 'Total Units' = SUM(sales_fact[Units])
		formatString: #,##0
		lineageTag: 95fc2835-0744-4ad5-8273-c9be1a18aaf8

	measure 'Gross Profit Margin' = DIVIDE([Gross Profit], [Total Sales])
		formatString: 0.0%
		lineageTag: 187a1fd7-9065-45cf-8ad5-4e9826c32fdd

	measure 'Previous Month Sales' =
			VAR LatestVisibleDate =
			    MAXX(ALLSELECTED(DateTable[Date]), DateTable[Date])
			VAR LatestCompleteMonthEnd =
			    IF(
			        LatestVisibleDate = EOMONTH(LatestVisibleDate, 0),
			        LatestVisibleDate,
			        EOMONTH(LatestVisibleDate, -1)
			    )
			VAR PreviousMonthStart =
			    EOMONTH(LatestCompleteMonthEnd, -2) + 1
			VAR PreviousMonthEnd =
			    EOMONTH(LatestCompleteMonthEnd, -1)
			RETURN
			    CALCULATE(
			        [Total Sales],
			        REMOVEFILTERS(DateTable),
			        DATESBETWEEN(DateTable[Date], PreviousMonthStart, PreviousMonthEnd)
			    )
		formatString: MXN #,##0
		lineageTag: 59cf2aa2-60fd-4f82-9826-daafcb9ba26b

	measure 'Sales MoM %' =
			VAR PreviousSales = [Previous Month Sales]
			RETURN
			    IF(
			        ISBLANK(PreviousSales) || PreviousSales = 0,
			        BLANK(),
			        DIVIDE([Latest Month Sales] - PreviousSales, PreviousSales)
			    )
		formatString: 0.0%;-0.0%
		lineageTag: 29cc8c1c-9adf-4bb4-80ed-a7d1ad7e062e

	measure 'Latest Month Sales' =
			VAR LatestVisibleDate =
			    MAXX(ALLSELECTED(DateTable[Date]), DateTable[Date])
			VAR LatestCompleteMonthEnd =
			    IF(
			        LatestVisibleDate = EOMONTH(LatestVisibleDate, 0),
			        LatestVisibleDate,
			        EOMONTH(LatestVisibleDate, -1)
			    )
			VAR LatestMonthStart =
			    EOMONTH(LatestCompleteMonthEnd, -1) + 1
			VAR LatestMonthEnd =
			    LatestCompleteMonthEnd
			RETURN
			    CALCULATE(
			        [Total Sales],
			        REMOVEFILTERS(DateTable),
			        DATESBETWEEN(DateTable[Date], LatestMonthStart, LatestMonthEnd)
			    )
		formatString: MXN #,##0
		lineageTag: 3ac5ec46-f0cc-4009-b4f3-1a4ea934f827

	column Sale_ID
		dataType: int64
		lineageTag: d9741516-f60d-48a6-bc5f-0f91d658cd56
		summarizeBy: none
		sourceColumn: Sale_ID

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 33886f0f-7456-4754-9ac9-0c233864c5f8
		summarizeBy: none
		sourceColumn: Date

		annotation UnderlyingDateTimeDataType = Date

	column Store_ID
		dataType: int64
		lineageTag: 4e84139c-2c66-4fe2-9ca7-6394521f69f1
		summarizeBy: none
		sourceColumn: Store_ID

	column Product_ID
		dataType: int64
		lineageTag: 5c5a9dc8-f77c-403e-942e-d0d6f1eb9a6e
		summarizeBy: none
		sourceColumn: Product_ID

	column Units
		dataType: int64
		formatString: #,0
		lineageTag: 774878f1-82ea-4603-a2a7-d02e2a071ae3
		summarizeBy: sum
		sourceColumn: Units

	column Sales
		dataType: double
		formatString: $#,0.00
		lineageTag: 8c238559-4285-4985-a04a-ed9a84b58e36
		summarizeBy: sum
		sourceColumn: Sales

	column Cost
		dataType: double
		formatString: $#,0.00
		lineageTag: 18e4efe6-23ac-4690-9d96-96ab8cf86d27
		summarizeBy: sum
		sourceColumn: Cost

	column Profit
		dataType: double
		formatString: $#,0.00
		lineageTag: d970be01-2fff-4c17-b3cc-f3d1feba6679
		summarizeBy: sum
		sourceColumn: Profit

	partition sales_fact = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Administrator\Desktop\数据分析项目\03_Mexico_Toy_Sales\output\sales_fact.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Types = Table.TransformColumnTypes(Headers,{{"Sale_ID", Int64.Type},{"Date", type date},{"Store_ID", Int64.Type},{"Product_ID", Int64.Type},{"Units", Int64.Type},{"Sales", type number},{"Cost", type number},{"Profit", type number}})
				in Types

