table stores
	lineageTag: 726333e5-ba6d-4360-8265-10a890111069

	column Store_ID
		dataType: int64
		isKey
		lineageTag: 15b53ace-50e5-4021-bfd1-c70bb2872fdd
		summarizeBy: none
		sourceColumn: Store_ID

	column Store_Name
		dataType: string
		lineageTag: efee69db-3fb0-4503-9751-ac2d7f43e78c
		summarizeBy: none
		sourceColumn: Store_Name

	column Store_City
		dataType: string
		lineageTag: 4081fb04-31a9-4165-b0af-55f3e2544455
		summarizeBy: none
		sourceColumn: Store_City

	column Store_Location
		dataType: string
		lineageTag: d2350406-ff6d-4d02-bfeb-2a8b029bdc86
		summarizeBy: none
		sourceColumn: Store_Location

	column Store_Open_Date
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: 3b9b7985-ca1e-4549-ba3f-cc6c92dfba1c
		summarizeBy: none
		sourceColumn: Store_Open_Date

		annotation UnderlyingDateTimeDataType = Date

	column 门店类型显示 = SWITCH(stores[Store_Location], "Airport","机场店", "Commercial","商业区店", "Downtown","市中心店", "Residential","社区店", stores[Store_Location])
		dataType: string
		lineageTag: a2622df6-d271-4c28-81ef-40bdaf91f273
		summarizeBy: none

	column 门店简称 = SUBSTITUTE(stores[Store_Name], "Maven Toys ", "")
		dataType: string
		lineageTag: 27632610-ef75-44c2-a405-153fb90b5d5d
		summarizeBy: none

	partition stores = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataRootPath & "stores.csv"),[Delimiter=",",Encoding=65001,QuoteStyle=QuoteStyle.Csv]),
					Headers = Table.PromoteHeaders(Source,[PromoteAllScalars=true]),
					Types = Table.TransformColumnTypes(Headers,{{"Store_ID",Int64.Type},{"Store_Name",type text},{"Store_City",type text},{"Store_Location",type text},{"Store_Open_Date",type date}})
				in Types

