table stores
	lineageTag: 7ddb1514-a99c-45b9-80f7-17f874109475

	column Store_ID
		dataType: int64
		lineageTag: 09d1761e-1d96-4a88-83fb-5c6659e94588
		summarizeBy: none
		sourceColumn: Store_ID

	column Store_Name
		dataType: string
		lineageTag: e2937514-7926-4992-af7f-5ab201b764b8
		summarizeBy: none
		sourceColumn: Store_Name

	column Store_City
		dataType: string
		lineageTag: 9a80eeaa-eb76-40fe-934c-8ec8d258dc02
		summarizeBy: none
		sourceColumn: Store_City

	column Store_Location
		dataType: string
		lineageTag: f72cfa35-4a9e-4c8b-abae-f5eb3e0ca324
		summarizeBy: none
		sourceColumn: Store_Location

	column Store_Open_Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0424a434-eeaa-4224-a8ed-e59e4b6064fb
		summarizeBy: none
		sourceColumn: Store_Open_Date

		annotation UnderlyingDateTimeDataType = Date

	partition stores = m
		mode: import
		source =
				let
				 Source=Csv.Document(File.Contents("C:\Users\Administrator\Desktop\数据分析项目\03_Mexico_Toy_Sales\output\stores.csv"),[Delimiter=",",Columns=5,Encoding=65001,QuoteStyle=QuoteStyle.Csv]), Headers=Table.PromoteHeaders(Source,[PromoteAllScalars=true]), Types=Table.TransformColumnTypes(Headers,{{"Store_ID",Int64.Type},{"Store_Name",type text},{"Store_City",type text},{"Store_Location",type text},{"Store_Open_Date",type date}})
				in Types

